name: gravity_group_techquest
description: Your description

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: ^1.17.2
  async: ^2.11.0
  meta: ^1.9.1

  # Localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

  # Persistence
  typed_preferences: ^0.2.0
  shared_preferences: ^2.2.0

  # Logging
  stack_trace: ^1.11.0
  logging: ^1.2.0

  # Utils
  pure: ^0.2.0
  platform_info: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15

  # Logic
  geolocator: ^9.0.2
  streamed_controller: ^0.3.0

  # Packages
  rest_client:
    path: packages/rest_client

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

  # Utils
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80
